/**
 * bizstd — an append-only container for records that arrive continuously.
 *
 * These declarations are hand-written and cover the wrapper; the addon's own
 * `index.d.ts` is generated by napi and covers the boundary. A test compares
 * the two so they cannot drift apart quietly.
 */

import type {
  Frame,
  HeadOnly,
  RebuildReport,
  RepackReport,
  Schema,
  ValidateReport,
} from '../index.js'

export type { FieldSpec, Frame, HeadOnly, Preamble, RebuildReport, RepackReport, Schema, ValidateReport } from '../index.js'

/** Base of every error this package throws. */
export declare class BizstdError extends Error {
  constructor(message: string, code: string)
  /** A stable identifier for the failure, e.g. `BIZSTD_ZONE_FULL`. */
  readonly code: string
}

/** The file is not a well-formed container. */
export declare class BizstdMalformedError extends BizstdError {}
/** The calling code asked for something it may not. */
export declare class BizstdUsageError extends BizstdError {}
/** The header zone cannot hold the headers; repack with a larger one. */
export declare class BizstdZoneFullError extends BizstdError {}
/** zstd refused to compress or decompress. */
export declare class BizstdCompressionError extends BizstdError {}
/** The operating system said no. */
export declare class BizstdIOError extends BizstdError {}

/** A container opened for reading. */
export declare class Reader {
  /** Every header, system and application alike. */
  readonly headers: Record<string, string>
  /** The closed frames, in file order. */
  readonly frames: Frame[]
  /** Records the headers claim, closed frames only. */
  readonly recordCount: bigint

  /**
   * The decompressed bytes of the frame at this position.
   *
   * By position rather than by id: ids belong to the writer and writers repeat
   * them.
   */
  frame(index: number): Buffer
  /** The decompressed bytes of the first frame carrying this id. */
  frameById(frameId: bigint): Buffer
  /** The uncompressed tail, whole records only. */
  tail(): Buffer
  /** Every record in the file, frame by frame and then the tail. */
  records(options?: { includeTail?: boolean }): Generator<Buffer, void, undefined>
  [Symbol.iterator](): Generator<Buffer, void, undefined>
}

/** A container opened for appending. */
export declare class Writer {
  /** Every header, system and application alike. */
  readonly headers: Record<string, string>
  /** The frames closed so far. */
  readonly frames: Frame[]
  /** Records appended, the unflushed buffer included. */
  readonly recordCount: bigint

  /** Appends one record. */
  append(body: Buffer | Uint8Array): void
  /** Appends many records. */
  extend(bodies: ReadonlyArray<Buffer | Uint8Array>): void
  /** Writes whatever is buffered, without closing a frame. */
  flush(): void
  /**
   * Compresses the tail into one frame, crash-safe.
   *
   * @throws {BizstdZoneFullError} when the header zone is full; the way out is
   * `repack` with a larger zone, not a retry.
   */
  closeFrame(frameId: bigint | number, level?: number): void
  /** Closes the tail and marks the file finished. */
  seal(frameId: bigint | number, level?: number): void
  /** Sets an application header. Keys may not start with `_`. */
  setHeader(key: string, value: string): void
}

/** Creates a file and returns it open for appending. */
export declare function create(
  path: string,
  schema: Schema,
  options: {
    source: string
    writer: string
    createdAtMillis?: bigint | number
    headerArea?: number
    headers?: Record<string, string>
  },
): Writer

/** Opens a file read-only. Nothing is recovered and nothing is written. */
export declare function openRead(path: string): Reader

/** Opens a file for appending, replaying a pending journal first. */
export declare function openAppend(path: string): Writer

/** Preamble and headers without touching the data section. */
export declare function peekHeaders(path: string): HeadOnly
/** Reads every frame, checks the counters, the alignment and the checksums. */
export declare function validate(path: string): ValidateReport
/** Derives the system headers from the data, and writes them back when asked. */
export declare function rebuildHeaders(path: string, fix?: boolean): RebuildReport
/** Re-encodes every frame at another level, atomically. */
export declare function repack(path: string, level?: number, headerArea?: number): RepackReport
/** Splits raw bytes into records; the second value is the torn leftover. */
export declare function splitRecords(data: Buffer, fixedSize?: number): [Buffer[], number]
/** XXH64 with seed 0 — the hash the frame checksums use. */
export declare function xxh64(data: Buffer): bigint
/** Roughly how many frames a header zone of this size can list. */
export declare function maxFramesFor(headerArea: number): bigint

/** Container format version this build writes. */
export declare const VERSION: number
/** The file extension, without the dot. */
export declare const EXTENSION: string
/** The default header zone size. */
export declare const DEFAULT_HEADER_AREA: number
/** The largest header zone a file may declare. */
export declare const MAX_HEADER_AREA: number
/** The zstd level for closing frames on the write path. */
export declare const HOT_LEVEL: number
/** The zstd level for repacking a file offline. */
export declare const COLD_LEVEL: number
