// The wrapper's declarations describe the wrapper that actually exists.
//
// `lib/index.d.ts` is written by hand; `index.d.ts` is generated by napi from
// the Rust. Both can drift from what they describe, and a drifted declaration
// is worse than none: the type checker agrees, confidently, with code that
// will fail. This compares names rather than signatures — a method appearing
// or disappearing is the drift that actually happens.

import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

import bizstd from '../lib/index.js'

const declarations = readFileSync(fileURLToPath(new URL('../lib/index.d.ts', import.meta.url)), 'utf8')
const generated = readFileSync(fileURLToPath(new URL('../index.d.ts', import.meta.url)), 'utf8')

/** Every name the hand-written declarations export. */
function declared() {
  const names = new Set()
  for (const match of declarations.matchAll(/^export declare (?:class|function|const) (\w+)/gm)) {
    names.add(match[1])
  }
  return names
}

test('everything the package exports is declared', () => {
  const exported = Object.keys(bizstd)
  const missing = exported.filter((name) => !declared().has(name))
  assert.deepEqual(missing, [], `exported but not declared: ${missing.join(', ')}`)
})

test('the declarations invent nothing', () => {
  const exported = new Set(Object.keys(bizstd))
  const invented = [...declared()].filter((name) => !exported.has(name))
  assert.deepEqual(invented, [], `declared but not exported: ${invented.join(', ')}`)
})

test('every error class carries a code and descends from the base', () => {
  const classes = [
    bizstd.BizstdMalformedError,
    bizstd.BizstdUsageError,
    bizstd.BizstdZoneFullError,
    bizstd.BizstdCompressionError,
    bizstd.BizstdIOError,
  ]
  for (const Kind of classes) {
    const error = new Kind('why', 'BIZSTD_TEST')
    assert.ok(error instanceof bizstd.BizstdError, `${Kind.name} is not a BizstdError`)
    assert.equal(error.code, 'BIZSTD_TEST')
    assert.equal(error.name, Kind.name, 'the name is the class name, not "Error"')
  }
})

test('the generated declarations cover the native surface the wrapper uses', () => {
  // Everything the wrapper reaches for on the addon. If napi stops generating
  // one of these, the wrapper breaks at runtime and this says so first.
  for (const name of [
    'Container',
    'peekHeaders',
    'validate',
    'rebuildHeaders',
    'repack',
    'splitRecords',
    'xxh64',
    'maxFramesFor',
  ]) {
    assert.ok(
      generated.includes(name),
      `the addon no longer declares ${name}; the wrapper still calls it`,
    )
  }
})

test('the constants agree with the format', () => {
  assert.equal(typeof bizstd.VERSION, 'number')
  assert.equal(bizstd.EXTENSION, 'bizstd')
  assert.equal(bizstd.DEFAULT_HEADER_AREA, 4096)
  assert.ok(bizstd.HOT_LEVEL < bizstd.COLD_LEVEL, 'the hot level compresses less than the cold one')
})
