"""Type stubs for the extension module.

PyO3 does not emit these, so they are written by hand and checked against the
real module by `python/bizstd-binary/tests/test_stubs.py`: a stub nobody
verifies drifts from the thing it describes within a release or two, and a
wrong stub is worse than none — it makes the type checker confidently agree
with code that will fail.
"""

from pathlib import Path
from types import TracebackType
from typing import final

VERSION: int
EXTENSION: str
DEFAULT_HEADER_AREA: int
MAX_HEADER_AREA: int
HOT_LEVEL: int
COLD_LEVEL: int
__version__: str

class BizstdError(Exception):
    """Base of every error this package raises."""

class BizstdMalformedError(BizstdError):
    """The file is not a well-formed container."""

class BizstdUsageError(BizstdError):
    """The calling code asked for something it may not."""

class BizstdZoneFullError(BizstdError):
    """The header zone cannot hold the headers; repack with a larger one."""

class BizstdCompressionError(BizstdError):
    """zstd refused to compress or decompress."""

@final
class RecordLayout:
    """How a record's bytes are delimited inside a frame."""

    @property
    def fixed_size(self) -> int | None:
        """Bytes per record, or ``None`` when records carry a length prefix."""

    @staticmethod
    def fixed(size: int) -> RecordLayout: ...
    @staticmethod
    def prefixed() -> RecordLayout: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

@final
class FieldSpec:
    """One field of a schema."""

    def __init__(self, name: str, ty: str, offset: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def ty(self) -> str: ...
    @property
    def offset(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

@final
class Schema:
    """What the records in a file look like."""

    def __init__(self, name: str, fields: list[FieldSpec], layout: RecordLayout) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def fields(self) -> list[FieldSpec]: ...
    @property
    def layout(self) -> RecordLayout: ...
    def hash_hex(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

@final
class Frame:
    """One closed frame in the data section."""

    @property
    def id(self) -> int: ...
    @property
    def offset(self) -> int: ...
    @property
    def len(self) -> int: ...
    @property
    def hash(self) -> int:
        """XXH64 of the compressed bytes; ``0`` when the file predates checksums."""

    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

@final
class Preamble:
    """The fixed binary head of a file."""

    @property
    def version(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def header_area(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

@final
class ValidateReport:
    """What :func:`validate` found."""

    @property
    def problems(self) -> list[str]: ...
    @property
    def frames(self) -> int: ...
    @property
    def records(self) -> int: ...

@final
class RebuildReport:
    """What :func:`rebuild_headers` found and did."""

    @property
    def differences(self) -> list[str]: ...
    @property
    def fixed(self) -> bool: ...

@final
class RepackReport:
    """What :func:`repack` measured."""

    @property
    def bytes_before(self) -> int: ...
    @property
    def bytes_after(self) -> int: ...
    @property
    def frames(self) -> int: ...

@final
class Container:
    """A container file, open for reading or appending."""

    @staticmethod
    def create(
        path: str | Path,
        schema: Schema,
        source: str,
        writer: str,
        created_at_millis: int = ...,
        header_area: int = ...,
        user: list[tuple[str, str]] | None = ...,
    ) -> Container: ...
    @staticmethod
    def open_read(path: str | Path) -> Container: ...
    @staticmethod
    def open_append(path: str | Path) -> Container: ...
    def headers(self) -> dict[str, str]: ...
    def schema(self) -> Schema: ...
    def frames(self) -> list[Frame]: ...
    def records(self) -> int: ...
    def append_record(self, body: bytes) -> None: ...
    def flush_data(self) -> None: ...
    def flush_headers(self) -> None: ...
    def close_frame(self, frame_id: int, level: int) -> None: ...
    def seal(self, frame_id: int, level: int) -> None: ...
    def set_user_header(self, key: str, value: str) -> None: ...
    def read_frame(self, frame_id: int) -> bytes: ...
    def read_frame_at(self, index: int) -> bytes: ...
    def read_tail(self) -> bytes: ...
    # `Container` rather than `Self`: the class is final, so this is exact,
    # and `Self` would need Python 3.11 or a typing_extensions dependency
    # in a package whose whole point is not having any.
    def __enter__(self) -> Container: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def __repr__(self) -> str: ...

def peek_headers(path: str | Path) -> tuple[Preamble, dict[str, str]]: ...
def validate(path: str | Path) -> ValidateReport: ...
def rebuild_headers(path: str | Path, fix: bool = ...) -> RebuildReport: ...
def repack(path: str | Path, level: int = ..., header_area: int | None = ...) -> RepackReport: ...
def split_records(data: bytes, layout: RecordLayout) -> tuple[list[bytes], int]: ...
def xxh64(data: bytes) -> int: ...
def max_frames_for(header_area: int) -> int: ...
