/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A container file, open for reading or appending. */
export declare class Container {
  /** Creates a file: preamble and header zone, no data yet. */
  static create(path: string, schema: Schema, source: string, writer: string, createdAtMillis?: bigint | undefined | null, headerArea?: number | undefined | null, headers?: Record<string, string> | undefined | null): Container
  /** Opens a file read-only. Nothing is recovered and nothing is written. */
  static openRead(path: string): Container
  /**
   * Opens a file for appending, replaying a pending seal journal and
   * cutting a torn record off the tail first.
   *
   * Takes no lock: one writer per file, and enforcing that is the caller's.
   */
  static openAppend(path: string): Container
  /** Every header, system and application alike. */
  headers(): Record<string, string>
  /** The closed frames, in file order. */
  frames(): Array<Frame>
  /** Bytes per record, or `null` for length-prefixed records. */
  fixedSize(): number | null
  /** Records ever appended, the unflushed buffer included. */
  recordCount(): bigint
  /** Appends one record body. */
  append(body: Buffer): void
  /** Writes whatever is buffered. */
  flush(): void
  /** Compresses the raw tail into one frame, crash-safe. */
  closeFrame(frameId: bigint, level?: number | undefined | null): void
  /** Closes the tail and marks the file finished. */
  seal(frameId: bigint, level?: number | undefined | null): void
  /** Sets an application header. Keys may not start with `_`. */
  setHeader(key: string, value: string): void
  /**
   * Decompresses the frame at this position in the list.
   *
   * By position rather than by id: ids belong to the writer and writers
   * repeat them.
   */
  readFrameAt(index: number): Buffer
  /** Decompresses the first frame carrying this id. */
  readFrame(frameId: bigint): Buffer
  /** The uncompressed tail, whole records only. */
  readTail(): Buffer
}

/** The zstd level for repacking a file offline. */
export const COLD_LEVEL: number

/** The default header zone size. */
export const DEFAULT_HEADER_AREA: number

/** The file extension, without the dot. */
export const EXTENSION: string

/** One field of a schema. */
export interface FieldSpec {
  /** The field's name. */
  name: string
  /**
   * Its type as the format spells it: `u8`, `u16`, `u32`, `u64`, `i64`,
   * `f64` or `uuid`.
   */
  ty: string
  /** Byte offset inside the record. */
  offset: number
}

/** One closed frame in the data section. */
export interface Frame {
  /** The id the writer gave it. Ids may repeat. */
  id: bigint
  /** Byte offset from the start of the data section. */
  offset: bigint
  /** Compressed length. */
  len: bigint
  /** XXH64 of the compressed bytes, `0n` when the file predates checksums. */
  hash: bigint
}

/** Preamble and headers, without touching the data section. */
export interface HeadOnly {
  /** The preamble. */
  preamble: Preamble
  /** Every header, system and application alike. */
  headers: Record<string, string>
}

/** The zstd level for closing frames on the write path. */
export const HOT_LEVEL: number

/** The largest header zone a file may declare. */
export const MAX_HEADER_AREA: number

/** Roughly how many frames a header zone of this size can list. */
export declare function maxFramesFor(headerArea: number): bigint

/** Preamble and headers without touching the data section. */
export declare function peekHeaders(path: string): HeadOnly

/** The fixed binary head of a file. */
export interface Preamble {
  /** Container format version. */
  version: number
  /** Flag bits; bit 0 means the data section is compressed. */
  flags: number
  /** Size of the header zone in bytes. */
  headerArea: number
}

/** Derives the system headers from the data, and writes them back when asked. */
export declare function rebuildHeaders(path: string, fix?: boolean | undefined | null): RebuildReport

/** What `rebuildHeaders` found and did. */
export interface RebuildReport {
  /** Header values that disagreed with the data. */
  differences: Array<string>
  /** Whether the zone was rewritten. */
  fixed: boolean
}

/** Re-encodes every frame at another level, atomically. */
export declare function repack(path: string, level?: number | undefined | null, headerArea?: number | undefined | null): RepackReport

/** What `repack` measured. */
export interface RepackReport {
  /** File size before, bytes. */
  bytesBefore: bigint
  /** File size after, bytes. */
  bytesAfter: bigint
  /** Frames re-encoded. */
  frames: number
}

/**
 * What the records in a file look like.
 *
 * `fixedSize` decides the layout: a number means records of exactly that many
 * bytes, and leaving it out means each record is preceded by a little-endian
 * `u16` length.
 */
export interface Schema {
  /** The schema's name, `name@version` by convention. */
  name: string
  /** Its fields, in declaration order. */
  fields: Array<FieldSpec>
  /** Bytes per record, or absent for length-prefixed records. */
  fixedSize?: number
}

/** Splits raw bytes into records. The second value is the torn leftover. */
export declare function splitRecords(data: Buffer, fixedSize?: number | undefined | null): [Array<Buffer>, number]

/** Reads every frame, checks the counters, the alignment and the checksums. */
export declare function validate(path: string): ValidateReport

/** What `validate` found. */
export interface ValidateReport {
  /** Everything wrong, empty when the file is sound. */
  problems: Array<string>
  /** Closed frames checked. */
  frames: number
  /** Records seen in frames and the tail. */
  records: bigint
}

/** Container format version this build writes. */
export const VERSION: number

/** XXH64 with seed 0 — the hash the frame checksums use. */
export declare function xxh64(data: Buffer): bigint
